package com.java.shopping.madrid.models;
// Generated 15-abr-2014 10:26:13 by Hibernate Tools 3.6.0

import org.apache.struts.action.ActionForm;

/**
 * DepartmentStore generated by hbm2java
 */
public class DepartmentStore extends ActionForm implements java.io.Serializable {


     private Integer idDepartmentStore;
     private String name;

    public DepartmentStore() {
    }

    public DepartmentStore(String name) {
       this.name = name;
    }
   
    public Integer getIdDepartmentStore() {
        return this.idDepartmentStore;
    }
    
    public void setIdDepartmentStore(Integer idDepartmentStore) {
        this.idDepartmentStore = idDepartmentStore;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


