package com.java.shopping.madrid.models;
// Generated 15-abr-2014 10:26:13 by Hibernate Tools 3.6.0

import org.apache.struts.action.ActionForm;


/**
 * Login generated by hbm2java
 */
public class Login extends ActionForm implements java.io.Serializable {


     private Integer idUser;
     private String user;
     private String password;
     private int level;
     private String name;

    public Login() {
    }

    public Login(String user, String password, int level, String name) {
       this.user = user;
       this.password = password;
       this.level = level;
       this.name = name;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


