package com.java.shopping.madrid.models;
// Generated 15-abr-2014 10:26:13 by Hibernate Tools 3.6.0

import org.apache.struts.action.ActionForm;

/**
 * Streets generated by hbm2java
 */
public class Streets extends ActionForm implements java.io.Serializable {


     private Integer idStreet;
     private String name;
     private int idArea;

    public Streets() {
    }

    public Streets(String name, int idArea) {
       this.name = name;
       this.idArea = idArea;
    }
   
    public Integer getIdStreet() {
        return this.idStreet;
    }
    
    public void setIdStreet(Integer idStreet) {
        this.idStreet = idStreet;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }




}


