package com.java.shopping.madrid.models;
// Generated 15-abr-2014 10:26:13 by Hibernate Tools 3.6.0

import org.apache.struts.action.ActionForm;

/**
 * TypeShop generated by hbm2java
 */
public class TypeShop extends ActionForm implements java.io.Serializable {


     private Integer idType;
     private String name_es;
     private String name_en;

    public TypeShop() {
    }

    public TypeShop(String name_es, String name_en) {
       this.name_es = name_es;
       this.name_en = name_en;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public String getName_es() {
        return this.name_es;
    }
    
    public void setName_es(String name_es) {
        this.name_es = name_es;
    }
    public String getName_en() {
        return this.name_en;
    }
    
    public void setName_en(String name_en) {
        this.name_en = name_en;
    }
}


